# Generated by Django 3.1.3 on 2020-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.CharField(default='', max_length=50),
        ),
    ]
