# Generated by Django 3.1.3 on 2020-11-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201128_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
