# Generated by Django 3.1.3 on 2020-11-28 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201128_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 44, 3, 541066, tzinfo=utc)),
        ),
    ]
