# Generated by Django 3.1.3 on 2020-11-29 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201129_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 21, 53, 2, 471592, tzinfo=utc)),
        ),
    ]
