# Generated by Django 3.1.3 on 2020-11-29 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20201128_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikes',
            name='dislike_by',
            field=models.ManyToManyField(related_name='dislike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like_by',
            field=models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
